# Supabase configuration
SUPABASE_URL = "https://kgcuizruqbzctrxwulnt.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnY3VpenJ1cWJ6Y3RyeHd1bG50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIxODQ5NTksImV4cCI6MjA0Nzc2MDk1OX0.zVpg5dV_yKRpi9QWXJjBc_5w2Al1Kah7szRZJ3vgkCc"

# Google Cloud configuration
GOOGLE_API_KEY = "AIzaSyD3DaKQt0NIdHmJtpwbu5c-Zvdoot9rNqs"
GEMINI_API_KEY = "AIzaSyDMQ7dgxkDvSQpEzWG4p2nuCQUblExXmGE"

# LelaPA API configuration
LELAPA_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdiODA3YmQ3ZTEzMzQxOTg5ZjlkNTM1ODYyMTZlYWJjIiwiY2xpZW50X2lkIjo1NTEsInJlcXVlc3RzX3Blcl9taW51dGUiOjAsImxhc3RfcmVxdWVzdF90aW1lIjpudWxsfQ.nxtWaxBbEDOgx60fmuPscWvJQhhCgMxwfIKXDXbAbU4"
