# Supabase credentials
SUPABASE_URL = "https://kgcuizruqbzctrxwulnt.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnY3VpenJ1cWJ6Y3RyeHd1bG50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIxODQ5NTksImV4cCI6MjA0Nzc2MDk1OX0.Oc4Ql7fWOUmCOvXZGZxBCDFkWBMPUBCZkBXXBQGVbBg"

# Development mode
DEVELOPMENT_MODE = "true"

# Google Cloud credentials
GOOGLE_CLOUD_PROJECT_ID = "ubuntu-language-learning"
GOOGLE_CLOUD_KEY = "AIzaSyD3DaKQt0NIdHmJtpwbu5c-Zvdoot9rNqs"
